"""Model/classifier configurations for corpus generation."""

from typing import Dict, List, Any


def get_original_config() -> Dict[str, List[Dict[str, Any]]]:
    """Original single RandomForest configuration."""
    return {
        "RandomForest": [{"n_estimators": 120, "random_state": 42}],
    }


def get_classification_configs() -> Dict[str, List[Dict[str, Any]]]:
    """12 classifiers × 12 configurations = 144 configs per task."""
    return {
        "RandomForest": [
            {"n_estimators": 50, "max_depth": 5, "random_state": 42},
            {"n_estimators": 100, "max_depth": 10, "random_state": 42},
            {"n_estimators": 150, "max_depth": 15, "random_state": 42},
            {"n_estimators": 200, "max_depth": 20, "random_state": 42},
            {"n_estimators": 100, "max_depth": None, "random_state": 42},
            {"n_estimators": 150, "max_depth": 25, "min_samples_split": 5, "random_state": 42},
            {"n_estimators": 200, "max_depth": 30, "min_samples_leaf": 2, "random_state": 42},
            {"n_estimators": 250, "max_depth": 10, "random_state": 42},
            {"n_estimators": 100, "max_depth": 15, "criterion": "entropy", "random_state": 42},
            {"n_estimators": 120, "max_depth": None, "bootstrap": False, "random_state": 42},
            {"n_estimators": 80, "max_depth": 8, "max_features": "log2", "random_state": 42},
            {"n_estimators": 300, "max_depth": 12, "random_state": 42},
        ],
        "GradientBoosting": [
            {"n_estimators": 50, "learning_rate": 0.1, "max_depth": 3, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.05, "max_depth": 4, "random_state": 42},
            {"n_estimators": 150, "learning_rate": 0.1, "max_depth": 5, "random_state": 42},
            {"n_estimators": 200, "learning_rate": 0.01, "max_depth": 3, "random_state": 42},
            {"n_estimators": 75, "learning_rate": 0.2, "max_depth": 4, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.15, "max_depth": 6, "random_state": 42},
            {"n_estimators": 125, "learning_rate": 0.08, "max_depth": 5, "random_state": 42},
            {"n_estimators": 80, "learning_rate": 0.1, "max_depth": 3, "subsample": 0.8, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.1, "max_depth": 4, "min_samples_split": 4, "random_state": 42},
            {"n_estimators": 150, "learning_rate": 0.05, "max_depth": 3, "random_state": 42},
            {"n_estimators": 90, "learning_rate": 0.12, "max_depth": 5, "random_state": 42},
            {"n_estimators": 110, "learning_rate": 0.07, "max_depth": 4, "random_state": 42},
        ],
        "AdaBoost": [
            {"n_estimators": 50, "learning_rate": 1.0, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.5, "random_state": 42},
            {"n_estimators": 150, "learning_rate": 0.8, "random_state": 42},
            {"n_estimators": 200, "learning_rate": 0.3, "random_state": 42},
            {"n_estimators": 75, "learning_rate": 1.5, "random_state": 42},
            {"n_estimators": 125, "learning_rate": 0.7, "random_state": 42},
            {"n_estimators": 80, "learning_rate": 1.2, "random_state": 42},
            {"n_estimators": 60, "learning_rate": 0.9, "random_state": 42},
            {"n_estimators": 175, "learning_rate": 0.4, "random_state": 42},
            {"n_estimators": 90, "learning_rate": 0.6, "random_state": 42},
            {"n_estimators": 110, "learning_rate": 1.1, "random_state": 42},
            {"n_estimators": 130, "learning_rate": 0.85, "random_state": 42},
        ],
        "ExtraTrees": [
            {"n_estimators": 50, "max_depth": 10, "random_state": 42},
            {"n_estimators": 100, "max_depth": 20, "random_state": 42},
            {"n_estimators": 150, "max_depth": None, "random_state": 42},
            {"n_estimators": 200, "max_depth": 15, "random_state": 42},
            {"n_estimators": 80, "max_depth": 12, "min_samples_split": 4, "random_state": 42},
            {"n_estimators": 120, "max_depth": 25, "random_state": 42},
            {"n_estimators": 100, "max_depth": None, "bootstrap": True, "random_state": 42},
            {"n_estimators": 90, "max_depth": 18, "random_state": 42},
            {"n_estimators": 110, "max_depth": 22, "random_state": 42},
            {"n_estimators": 130, "max_depth": 8, "random_state": 42},
            {"n_estimators": 140, "max_depth": 30, "random_state": 42},
            {"n_estimators": 160, "max_depth": 14, "random_state": 42},
        ],
        "LogisticRegression": [
            {"C": 0.01, "max_iter": 1000, "random_state": 42},
            {"C": 0.1, "max_iter": 1000, "random_state": 42},
            {"C": 1.0, "max_iter": 1000, "random_state": 42},
            {"C": 10.0, "max_iter": 1000, "random_state": 42},
            {"C": 100.0, "max_iter": 1000, "random_state": 42},
            {"C": 0.5, "penalty": "l2", "max_iter": 1000, "random_state": 42},
            {"C": 5.0, "max_iter": 2000, "random_state": 42},
            {"C": 0.05, "max_iter": 1500, "random_state": 42},
            {"C": 2.0, "max_iter": 1000, "solver": "lbfgs", "random_state": 42},
            {"C": 0.2, "max_iter": 1000, "random_state": 42},
            {"C": 20.0, "max_iter": 1000, "random_state": 42},
            {"C": 0.8, "max_iter": 1200, "random_state": 42},
        ],
        "SVM": [
            {"C": 0.1, "kernel": "rbf", "random_state": 42},
            {"C": 1.0, "kernel": "rbf", "random_state": 42},
            {"C": 10.0, "kernel": "rbf", "random_state": 42},
            {"C": 1.0, "kernel": "linear", "random_state": 42},
            {"C": 1.0, "kernel": "poly", "degree": 2, "random_state": 42},
            {"C": 1.0, "kernel": "poly", "degree": 3, "random_state": 42},
            {"C": 0.5, "kernel": "rbf", "gamma": "scale", "random_state": 42},
            {"C": 5.0, "kernel": "rbf", "random_state": 42},
            {"C": 0.01, "kernel": "rbf", "random_state": 42},
            {"C": 2.0, "kernel": "rbf", "gamma": "auto", "random_state": 42},
            {"C": 1.0, "kernel": "sigmoid", "random_state": 42},
            {"C": 0.2, "kernel": "linear", "random_state": 42},
        ],
        "KNN": [
            {"n_neighbors": 1, "weights": "uniform"},
            {"n_neighbors": 3, "weights": "uniform"},
            {"n_neighbors": 5, "weights": "uniform"},
            {"n_neighbors": 7, "weights": "distance"},
            {"n_neighbors": 10, "weights": "uniform"},
            {"n_neighbors": 15, "weights": "distance"},
            {"n_neighbors": 20, "weights": "uniform"},
            {"n_neighbors": 5, "weights": "distance", "metric": "manhattan"},
            {"n_neighbors": 9, "weights": "uniform"},
            {"n_neighbors": 12, "weights": "distance"},
            {"n_neighbors": 8, "weights": "uniform"},
            {"n_neighbors": 25, "weights": "distance"},
        ],
        "MLP": [
            {"hidden_layer_sizes": (50,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (50, 50), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100, 50), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100, 100), "max_iter": 1000, "random_state": 42},
            {"hidden_layer_sizes": (200,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100, 100, 50), "max_iter": 1000, "random_state": 42},
            {"hidden_layer_sizes": (64, 32), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (128,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (256, 128), "max_iter": 1000, "random_state": 42},
            {"hidden_layer_sizes": (50, 25), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (150,), "max_iter": 750, "random_state": 42},
        ],
        "DecisionTree": [
            {"max_depth": 3, "random_state": 42},
            {"max_depth": 5, "random_state": 42},
            {"max_depth": 10, "random_state": 42},
            {"max_depth": 15, "random_state": 42},
            {"max_depth": 20, "random_state": 42},
            {"max_depth": None, "random_state": 42},
            {"max_depth": 8, "min_samples_split": 5, "random_state": 42},
            {"max_depth": 12, "criterion": "entropy", "random_state": 42},
            {"max_depth": 7, "min_samples_leaf": 3, "random_state": 42},
            {"max_depth": 25, "random_state": 42},
            {"max_depth": 6, "random_state": 42},
            {"max_depth": 18, "random_state": 42},
        ],
        "NaiveBayes": [
            {"var_smoothing": 1e-9}, {"var_smoothing": 1e-8}, {"var_smoothing": 1e-7},
            {"var_smoothing": 1e-10}, {"var_smoothing": 1e-6}, {"var_smoothing": 1e-11},
            {"var_smoothing": 1e-5}, {"var_smoothing": 5e-9}, {"var_smoothing": 5e-8},
            {"var_smoothing": 2e-9}, {"var_smoothing": 2e-8}, {"var_smoothing": 1e-12},
        ],
        "BaggingClassifier": [
            {"n_estimators": 10, "random_state": 42},
            {"n_estimators": 20, "random_state": 42},
            {"n_estimators": 50, "random_state": 42},
            {"n_estimators": 100, "random_state": 42},
            {"n_estimators": 30, "max_samples": 0.8, "random_state": 42},
            {"n_estimators": 40, "max_features": 0.8, "random_state": 42},
            {"n_estimators": 25, "bootstrap": True, "random_state": 42},
            {"n_estimators": 60, "random_state": 42},
            {"n_estimators": 15, "random_state": 42},
            {"n_estimators": 35, "max_samples": 0.7, "random_state": 42},
            {"n_estimators": 45, "random_state": 42},
            {"n_estimators": 80, "random_state": 42},
        ],
        "HistGradientBoosting": [
            {"max_iter": 50, "learning_rate": 0.1, "max_depth": 5, "random_state": 42},
            {"max_iter": 100, "learning_rate": 0.05, "max_depth": 8, "random_state": 42},
            {"max_iter": 150, "learning_rate": 0.1, "max_depth": 10, "random_state": 42},
            {"max_iter": 200, "learning_rate": 0.01, "random_state": 42},
            {"max_iter": 75, "learning_rate": 0.2, "max_depth": 6, "random_state": 42},
            {"max_iter": 100, "learning_rate": 0.15, "random_state": 42},
            {"max_iter": 125, "learning_rate": 0.08, "max_depth": 7, "random_state": 42},
            {"max_iter": 80, "learning_rate": 0.1, "random_state": 42},
            {"max_iter": 100, "learning_rate": 0.1, "max_depth": 4, "random_state": 42},
            {"max_iter": 150, "learning_rate": 0.05, "random_state": 42},
            {"max_iter": 90, "learning_rate": 0.12, "random_state": 42},
            {"max_iter": 110, "learning_rate": 0.07, "max_depth": 9, "random_state": 42},
        ],
    }


def get_regression_configs() -> Dict[str, List[Dict[str, Any]]]:
    """12 regressors × 12 configurations = 144 configs per task."""
    return {
        "RandomForestRegressor": [
            {"n_estimators": 50, "max_depth": 5, "random_state": 42},
            {"n_estimators": 100, "max_depth": 10, "random_state": 42},
            {"n_estimators": 150, "max_depth": 15, "random_state": 42},
            {"n_estimators": 200, "max_depth": 20, "random_state": 42},
            {"n_estimators": 100, "max_depth": None, "random_state": 42},
            {"n_estimators": 150, "max_depth": 25, "min_samples_split": 5, "random_state": 42},
            {"n_estimators": 200, "max_depth": 30, "min_samples_leaf": 2, "random_state": 42},
            {"n_estimators": 250, "max_depth": 10, "random_state": 42},
            {"n_estimators": 100, "max_depth": 15, "random_state": 42},
            {"n_estimators": 120, "max_depth": None, "bootstrap": False, "random_state": 42},
            {"n_estimators": 80, "max_depth": 8, "max_features": "log2", "random_state": 42},
            {"n_estimators": 300, "max_depth": 12, "random_state": 42},
        ],
        "GradientBoostingRegressor": [
            {"n_estimators": 50, "learning_rate": 0.1, "max_depth": 3, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.05, "max_depth": 4, "random_state": 42},
            {"n_estimators": 150, "learning_rate": 0.1, "max_depth": 5, "random_state": 42},
            {"n_estimators": 200, "learning_rate": 0.01, "max_depth": 3, "random_state": 42},
            {"n_estimators": 75, "learning_rate": 0.2, "max_depth": 4, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.15, "max_depth": 6, "random_state": 42},
            {"n_estimators": 125, "learning_rate": 0.08, "max_depth": 5, "random_state": 42},
            {"n_estimators": 80, "learning_rate": 0.1, "max_depth": 3, "subsample": 0.8, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.1, "max_depth": 4, "random_state": 42},
            {"n_estimators": 150, "learning_rate": 0.05, "max_depth": 3, "random_state": 42},
            {"n_estimators": 90, "learning_rate": 0.12, "max_depth": 5, "random_state": 42},
            {"n_estimators": 110, "learning_rate": 0.07, "max_depth": 4, "random_state": 42},
        ],
        "AdaBoostRegressor": [
            {"n_estimators": 50, "learning_rate": 1.0, "random_state": 42},
            {"n_estimators": 100, "learning_rate": 0.5, "random_state": 42},
            {"n_estimators": 150, "learning_rate": 0.8, "random_state": 42},
            {"n_estimators": 200, "learning_rate": 0.3, "random_state": 42},
            {"n_estimators": 75, "learning_rate": 1.5, "random_state": 42},
            {"n_estimators": 125, "learning_rate": 0.7, "random_state": 42},
            {"n_estimators": 80, "learning_rate": 1.2, "random_state": 42},
            {"n_estimators": 60, "learning_rate": 0.9, "random_state": 42},
            {"n_estimators": 175, "learning_rate": 0.4, "random_state": 42},
            {"n_estimators": 90, "learning_rate": 0.6, "random_state": 42},
            {"n_estimators": 110, "learning_rate": 1.1, "random_state": 42},
            {"n_estimators": 130, "learning_rate": 0.85, "random_state": 42},
        ],
        "ExtraTreesRegressor": [
            {"n_estimators": 50, "max_depth": 10, "random_state": 42},
            {"n_estimators": 100, "max_depth": 20, "random_state": 42},
            {"n_estimators": 150, "max_depth": None, "random_state": 42},
            {"n_estimators": 200, "max_depth": 15, "random_state": 42},
            {"n_estimators": 80, "max_depth": 12, "random_state": 42},
            {"n_estimators": 120, "max_depth": 25, "random_state": 42},
            {"n_estimators": 100, "max_depth": None, "bootstrap": True, "random_state": 42},
            {"n_estimators": 90, "max_depth": 18, "random_state": 42},
            {"n_estimators": 110, "max_depth": 22, "random_state": 42},
            {"n_estimators": 130, "max_depth": 8, "random_state": 42},
            {"n_estimators": 140, "max_depth": 30, "random_state": 42},
            {"n_estimators": 160, "max_depth": 14, "random_state": 42},
        ],
        "Ridge": [
            {"alpha": 0.01}, {"alpha": 0.1}, {"alpha": 1.0}, {"alpha": 10.0},
            {"alpha": 100.0}, {"alpha": 0.5}, {"alpha": 5.0}, {"alpha": 0.05},
            {"alpha": 2.0}, {"alpha": 0.2}, {"alpha": 20.0}, {"alpha": 0.8},
        ],
        "Lasso": [
            {"alpha": 0.01, "max_iter": 1000}, {"alpha": 0.1, "max_iter": 1000},
            {"alpha": 1.0, "max_iter": 1000}, {"alpha": 10.0, "max_iter": 1000},
            {"alpha": 0.001, "max_iter": 2000}, {"alpha": 0.5, "max_iter": 1000},
            {"alpha": 5.0, "max_iter": 1000}, {"alpha": 0.05, "max_iter": 1500},
            {"alpha": 2.0, "max_iter": 1000}, {"alpha": 0.2, "max_iter": 1000},
            {"alpha": 0.02, "max_iter": 1000}, {"alpha": 0.8, "max_iter": 1200},
        ],
        "ElasticNet": [
            {"alpha": 0.1, "l1_ratio": 0.5, "max_iter": 1000},
            {"alpha": 1.0, "l1_ratio": 0.5, "max_iter": 1000},
            {"alpha": 0.1, "l1_ratio": 0.2, "max_iter": 1000},
            {"alpha": 0.1, "l1_ratio": 0.8, "max_iter": 1000},
            {"alpha": 0.5, "l1_ratio": 0.5, "max_iter": 1000},
            {"alpha": 0.01, "l1_ratio": 0.5, "max_iter": 1000},
            {"alpha": 0.1, "l1_ratio": 0.1, "max_iter": 1000},
            {"alpha": 0.1, "l1_ratio": 0.9, "max_iter": 1000},
            {"alpha": 2.0, "l1_ratio": 0.5, "max_iter": 1000},
            {"alpha": 0.05, "l1_ratio": 0.3, "max_iter": 1000},
            {"alpha": 0.2, "l1_ratio": 0.7, "max_iter": 1000},
            {"alpha": 0.8, "l1_ratio": 0.4, "max_iter": 1000},
        ],
        "SVR": [
            {"C": 0.1, "kernel": "rbf"}, {"C": 1.0, "kernel": "rbf"},
            {"C": 10.0, "kernel": "rbf"}, {"C": 1.0, "kernel": "linear"},
            {"C": 1.0, "kernel": "poly", "degree": 2}, {"C": 1.0, "kernel": "poly", "degree": 3},
            {"C": 0.5, "kernel": "rbf", "gamma": "scale"}, {"C": 5.0, "kernel": "rbf"},
            {"C": 0.01, "kernel": "rbf"}, {"C": 2.0, "kernel": "rbf", "gamma": "auto"},
            {"C": 1.0, "kernel": "sigmoid"}, {"C": 0.2, "kernel": "linear"},
        ],
        "KNeighborsRegressor": [
            {"n_neighbors": 1}, {"n_neighbors": 3}, {"n_neighbors": 5},
            {"n_neighbors": 7, "weights": "distance"}, {"n_neighbors": 10},
            {"n_neighbors": 15, "weights": "distance"}, {"n_neighbors": 20},
            {"n_neighbors": 5, "weights": "distance", "metric": "manhattan"},
            {"n_neighbors": 9}, {"n_neighbors": 12, "weights": "distance"},
            {"n_neighbors": 8}, {"n_neighbors": 25, "weights": "distance"},
        ],
        "MLPRegressor": [
            {"hidden_layer_sizes": (50,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (50, 50), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100, 50), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100, 100), "max_iter": 1000, "random_state": 42},
            {"hidden_layer_sizes": (200,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (100, 100, 50), "max_iter": 1000, "random_state": 42},
            {"hidden_layer_sizes": (64, 32), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (128,), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (256, 128), "max_iter": 1000, "random_state": 42},
            {"hidden_layer_sizes": (50, 25), "max_iter": 500, "random_state": 42},
            {"hidden_layer_sizes": (150,), "max_iter": 750, "random_state": 42},
        ],
        "DecisionTreeRegressor": [
            {"max_depth": 3, "random_state": 42}, {"max_depth": 5, "random_state": 42},
            {"max_depth": 10, "random_state": 42}, {"max_depth": 15, "random_state": 42},
            {"max_depth": 20, "random_state": 42}, {"max_depth": None, "random_state": 42},
            {"max_depth": 8, "min_samples_split": 5, "random_state": 42},
            {"max_depth": 12, "random_state": 42},
            {"max_depth": 7, "min_samples_leaf": 3, "random_state": 42},
            {"max_depth": 25, "random_state": 42}, {"max_depth": 6, "random_state": 42},
            {"max_depth": 18, "random_state": 42},
        ],
        "HistGradientBoostingRegressor": [
            {"max_iter": 50, "learning_rate": 0.1, "max_depth": 5, "random_state": 42},
            {"max_iter": 100, "learning_rate": 0.05, "max_depth": 8, "random_state": 42},
            {"max_iter": 150, "learning_rate": 0.1, "max_depth": 10, "random_state": 42},
            {"max_iter": 200, "learning_rate": 0.01, "random_state": 42},
            {"max_iter": 75, "learning_rate": 0.2, "max_depth": 6, "random_state": 42},
            {"max_iter": 100, "learning_rate": 0.15, "random_state": 42},
            {"max_iter": 125, "learning_rate": 0.08, "max_depth": 7, "random_state": 42},
            {"max_iter": 80, "learning_rate": 0.1, "random_state": 42},
            {"max_iter": 100, "learning_rate": 0.1, "max_depth": 4, "random_state": 42},
            {"max_iter": 150, "learning_rate": 0.05, "random_state": 42},
            {"max_iter": 90, "learning_rate": 0.12, "random_state": 42},
            {"max_iter": 110, "learning_rate": 0.07, "max_depth": 9, "random_state": 42},
        ],
    }
